version: "3"
services:

    
  client:
    environment:
      - NUXT_HOST=0.0.0.0
      - STRAPI_URL=http://server:9001/
      - API_URL_BROWSER=/api
    user: node
    volumes:
      - .:/code
    command: sh -c "python3 frontend/docker/start_server.py"

  server:
    command: sh -c "python3 backend/docker/command/start_server.py"
    networks:
      apivault-network:
        aliases:
          - apivault-network
    
