version: '3'

networks:
  apivault-network:
    driver: bridge

services:
  #---------------
  # Postgres DB
  #---------------
  database:
    image: postgis/postgis:15-3.3
    container_name: apivault_database
    volumes:
      - ./data-db/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      apivault-network:
        aliases:
          - apivault-network

  #---------------
  # Backend
  #---------------
  server:
    container_name: apivault_server
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    depends_on:
      - database
    volumes:
      - .:/code
    tty: true
    stdin_open: true
    networks:
      apivault-network:
        aliases:
          - apivault-network

    command: python3 backend/docker/command/start_server.py
    ports:
      - "9001:9001"

  #--------------
  # Frontend App
  #--------------
  client:
    container_name: apivault_client
    labels:
      - "com.host.project=apivault-nuxt"
    depends_on:
      - server
    volumes:
      - .:/code
    tty: true
    stdin_open: true
    stop_grace_period: 10s
    stop_signal: SIGTERM
    networks:
      apivault-network:
        aliases:
          - apivault-network
    ports:
      - "3000:3000"
      - "24678:24678"
      - "9222:9222"
      - "5454:5555"
